---
title: "class06_hw"
author: 'Kaitlyn Madriaga, PID: A17217752'
date: "2023-04-27"
output:
  pdf_document: default
  pdf: default
---

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety = "CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab ="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")

```

function b.plot() takes a PDB id input (string) and returns a line plot of the B-factor with secondary structure elements shown as shaded regions

```{r}
#takes protein data bank (PDB) id input (string)
b.plot <- function(protein.id) {
  #reads PDB file
  x <-read.pdb(protein.id)
  #produces a subset of atoms from PDB file, extracting chain A C-alpha (CA) atoms
  x.chainA <-trim.pdb(x, chain = "A", elety = "CA")
  #extracts the B-factors of the CA atoms
  #returns a line plot of the B-factors with secondary structure elements shown as shaded regions
  #x = position of CA atoms along protein chain/residue, y = B-factors
  plotb3(x.chainA$atom$b, sse=x.chainA, typ="l", ylab="Bfactor")
}
```

example:

```{r}
b.plot("4AKE")
```
